[package]
name = "leetcode-rust"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
ndarray = "0.16.1"

[dependencies]
rand = "0.9.0"
